# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e16b2b5c58eaef6090b2932ec07b1bc6339b09ea51d8ad074a94d94aeb7fe6a1ff96bcfbf626b8e1edb340866a6587b6c2a9ad99eeb0c00ce02fb9be7ba8735

test:
  secret_key_base: 1c20c064d089873be887ce223ae6517faebc4da64a07e2b5c2435ed5d0f518cd30a359bfda6445e333e1f14d826b77709460d459ebffc49381380756f3bfae1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
